version: "3.9"
services:
  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment: 
      - FLASK_SERVER_ADDR=app
    
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 80:80
    networks:
      - docky    

    depends_on:
      - app
      
  app:
    build: ./app
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    volumes:
      - app:/app

    networks:
      - docky

volumes:
  app:

