version: "3.8"
services:
  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - app:/app
      
  app:
    build: ./app
    volumes:
      - app:/app

    


