version: "3.8"
services:
  nginx:
    container_name: nginx
    hostname: nginx
    networks:
      appnetwork:
        ipv4_address: 10.40.50.10
    image: nginx:stable-alpine
    tty: true #...
    stdin_open: true #these 2 options are for detach mode
    
    ports:
      - 80:80

    #Copy Config file to nginx directory
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
   
    #Reloading nginx service
    command: /usr/sbin/nginx -s reload

    depends_on:
      - app
      
  app:
    container_name: FlaskTIme
    networks:
      appnetwork:
        ipv4_address: 10.40.50.20
    build: ./app
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    volumes:
      - app:/app
networks:
  appnetwork:
    ipam:
      config:
        - subnet: 10.40.50.0/24





volumes:
  app:

