version: "3.9"
services:
  nginx:
    container_name: nginx
    hostname: nginx
    networks:
      customnetwork:
        ipv4_address: 10.40.50.10
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment: 
      - FLASK_SERVER_ADDR=app
    
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 80:80
   

    depends_on:
      - app
      
  app:
    container_name: FlaskTIme
    networks:
      customnetwork:
        ipv4_address: 10.40.50.20
    build: ./app
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    volumes:
      - app:/app
networks:
  customnetwork:
    ipam:
      config:
        - subnet: 10.40.50.0/24





volumes:
  app:

